//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int IdDanhGia { get; set; }
        public string IdSanPham { get; set; }
        public string TenNguoiDung { get; set; }
        public int SoSao { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public string IdNguoiDung { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
