//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuDangNhap
    {
        public int IdLichSu { get; set; }
        public string IdNguoiDung { get; set; }
        public string DiaChiIP { get; set; }
        public string ThietBi { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
