//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuDuyetTin
    {
        public int IdDuyet { get; set; }
        public string IdXe { get; set; }
        public string IdAdmin { get; set; }
        public string NoiDung { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
