//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int IdLienHe { get; set; }
        public string IdXe { get; set; }
        public string TenNguoiMua { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
