//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamHinhAnh
    {
        public string IdSanPham { get; set; }
        public string HinhAnh { get; set; }
        public int IdHinhAnh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
