//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.SanPhamHinhAnhs = new HashSet<SanPhamHinhAnh>();
            this.BienTheSanPhams = new HashSet<BienTheSanPham>();
            this.DanhGias = new HashSet<DanhGia>();


        }
    
        public string IdSanPham { get; set; }
        public string TenSanPham { get; set; }
        public decimal Gia { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaChiTiet { get; set; }
        public string HinhAnh { get; set; }
        public string IdDanhMuc { get; set; }
        public string ChatLieu { get; set; }
        public string MauSac { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<int> DaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamHinhAnh> SanPhamHinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienTheSanPham> BienTheSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
    }
}
