//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteMuaBanOtoDBEntities : DbContext
    {
        public WebsiteMuaBanOtoDBEntities()
            : base("name=WebsiteMuaBanOtoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhMucXe> DanhMucXes { get; set; }
        public virtual DbSet<DongXe> DongXes { get; set; }
        public virtual DbSet<HangXe> HangXes { get; set; }
        public virtual DbSet<LichSuDangNhap> LichSuDangNhaps { get; set; }
        public virtual DbSet<LichSuDuyetTin> LichSuDuyetTins { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<XeHinhAnh> XeHinhAnhs { get; set; }
        public virtual DbSet<YeuThich> YeuThiches { get; set; }
        public virtual DbSet<DatCoc> DatCocs { get; set; }
        public virtual DbSet<LaiThu> LaiThus { get; set; }
        public virtual DbSet<YeuCauTuVan> YeuCauTuVans { get; set; }
    }
}
