//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Xe()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.LichSuDuyetTins = new HashSet<LichSuDuyetTin>();
            this.LienHes = new HashSet<LienHe>();
            this.XeHinhAnhs = new HashSet<XeHinhAnh>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public string IdXe { get; set; }
        public string TieuDe { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> NamSX { get; set; }
        public Nullable<int> SoKM { get; set; }
        public string HopSo { get; set; }
        public string NhienLieu { get; set; }
        public string MauSac { get; set; }
        public string DongCo { get; set; }
        public string CongSuat { get; set; }
        public string KichThuoc { get; set; }
        public string XuatXu { get; set; }
        public string MoTaNgan { get; set; }
        public string MoTaChiTiet { get; set; }
        public string DiaDiem { get; set; }
        public string TrangThaiTin { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string IdNguoiBan { get; set; }
        public string IdDanhMuc { get; set; }
        public string IdHangXe { get; set; }
        public string IdDongXe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMucXe DanhMucXe { get; set; }
        public virtual DongXe DongXe { get; set; }
        public virtual HangXe HangXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDuyetTin> LichSuDuyetTins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienHe> LienHes { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeHinhAnh> XeHinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
