//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauTuVan
    {
        public int IdTuVan { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string MucLuong { get; set; }
        public string DongXeYeuThich { get; set; }
        public string MucGiaMongMuon { get; set; }
        public string PhanHoiCuaAdmin { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    }
}
