//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuThich
    {
        public int IdYeuThich { get; set; }
        public string IdNguoiDung { get; set; }
        public string IdXe { get; set; }
        public Nullable<System.DateTime> NgayLuu { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
